# Generated by Django 5.1.7 on 2025-03-29 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_task_file_task_rating'),
        ('main_app', '0005_salary'),
    ]

    operations = [
    ]
