# Generated by Django 5.2 on 2025-04-17 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rankreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rankreport',
            name='employee',
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.manager'),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.employee'),
        ),
        migrations.AddConstraint(
            model_name='attendancereport',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('employee__isnull', False), ('manager__isnull', True)), models.Q(('employee__isnull', True), ('manager__isnull', False)), _connector='OR'), name='attendance_either_employee_or_manager'),
        ),
        migrations.DeleteModel(
            name='RankReport',
        ),
    ]
