# Generated by Django 5.2 on 2025-04-19 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_feedbackemployee_is_read_feedbackmanager_is_read_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackemployee',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='feedbackmanager',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='leavereportemployee',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='leavereportmanager',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='notificationemployee',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='notificationmanager',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_viewed',
        ),
        migrations.DeleteModel(
            name='NotificationCounter',
        ),
    ]
