# Generated by Django 5.2 on 2025-04-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_feedbackemployee_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationemployee',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationmanager',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
