# Generated by Django 5.2 on 2025-04-19 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_notificationemployee_read_notificationmanager_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavereportemployee',
            name='date',
        ),
        migrations.RemoveField(
            model_name='leavereportmanager',
            name='date',
        ),
        migrations.AddField(
            model_name='leavereportemployee',
            name='date_from',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='leavereportemployee',
            name='date_to',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='leavereportemployee',
            name='leave_type',
            field=models.CharField(choices=[('sick', 'Sick Leave'), ('annual', 'Annual Leave')], default='annual', max_length=10),
        ),
        migrations.AddField(
            model_name='leavereportmanager',
            name='date_from',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='leavereportmanager',
            name='date_to',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='leavereportmanager',
            name='leave_type',
            field=models.CharField(choices=[('sick', 'Sick Leave'), ('annual', 'Annual Leave')], default='annual', max_length=10),
        ),
    ]
